###############################################################################
#                              Configuration                                  #
###############################################################################

cuba.springContextConfig = +com/company/untitled16/web-spring.xml

cuba.dispatcherSpringContextConfig = +com/company/untitled16/web-dispatcher-spring.xml

cuba.persistenceConfig = +com/company/untitled16/persistence.xml

cuba.metadataConfig = +com/company/untitled16/metadata.xml

cuba.viewsConfig = +com/company/untitled16/views.xml

cuba.windowConfig = +com/company/untitled16/web-screens.xml

cuba.menuConfig = +com/company/untitled16/web-menu.xml

cuba.permissionConfig = +com/company/untitled16/web-permissions.xml

cuba.mainMessagePack = +com.company.untitled16.web

cuba.anonymousSessionId = b19fb134-879e-ffec-9b58-266c3de2e5fe

cuba.creditsConfig = +

###############################################################################
#                                  Other                                      #
###############################################################################

# Middleware connection
cuba.connectionUrlList = http://localhost:8080/app-core

# Set to false if the middleware works on different JVM
cuba.useLocalServiceInvocation = true

cuba.webContextName = app
cuba.availableLocales = English|en
cuba.localeSelectVisible = false
cuba.web.theme = hover