###############################################################################
#                              Configuration                                  #
###############################################################################

cuba.dbmsType = hsql

cuba.springContextConfig = +com/company/untitled16/spring.xml

cuba.persistenceConfig = +com/company/untitled16/persistence.xml

cuba.metadataConfig = +com/company/untitled16/metadata.xml

cuba.viewsConfig = +com/company/untitled16/views.xml

cuba.mainMessagePack = +com.company.untitled16.core

cuba.keyForSecurityTokenEncryption = z5jHwZr5v1vm9mn5

cuba.anonymousSessionId = b19fb134-879e-ffec-9b58-266c3de2e5fe

###############################################################################
#                                  Other                                      #
###############################################################################

cuba.webContextName = app-core
cuba.availableLocales = English|en
cuba.localeSelectVisible = false

cuba.dataSourceProvider = application
cuba.dataSource.username = sa
cuba.dataSource.password =
cuba.dataSource.dbName = untitled16-158281
cuba.dataSource.host = localhost
cuba.dataSource.port = 9010