alter table UNTITLED16_RECENT_DOC add constraint FK_UNTITLED16_RECENT_DOC_ON_USER foreign key (USER_ID) references SEC_USER(ID);
create index IDX_UNTITLED16_RECENT_DOC_ON_USER on UNTITLED16_RECENT_DOC (USER_ID);
